import React from 'react'
import Header from './Header'
import Footer from './Footer'

function Terms() {
  return (
    <div>
      <Header />
      <div className="row">
        <div className="col-md-2"></div>
        <div className="col-md-8">
          <header>
            <h1>Terms</h1>
          </header>
          <main id="main">
            <div className="text-holder">
              <p>Keychn Experience S.L. (“Keychn,” “we,” “us,” “our”) provides its services (described below) to you through its website located at www.Keychn.com (the “Site”) and through its mobile applications, platform, products and related services (collectively, such services, including any new features and applications, and the Site, the “Service(s)”), subject to the following Terms of Service (as amended from time to time, the “Terms of Service”). We reserve the right, at our sole discretion, to change or modify portions of these Terms of Service at any time. If we do this, we will post the changes on this page and will indicate at the top of this page the date these terms were last revised. We will also notify you, either through the Services user interface, in an email notification or through other reasonable means. Any such changes will become effective no earlier than fourteen (14) days after they are posted, except that changes addressing new functions of the Services or changes made for legal reasons will be effective immediately. Your continued use of the Service after the date any such changes become effective constitutes your acceptance of the new Terms of Service..</p>
              <p>In addition, when using certain services, you will be subject to any additional terms applicable to such services that may be posted on the Service from time to time, including, without limitation, the Privacy Policy located at http://Keychn.com/privacy/ . All such terms are hereby incorporated by reference into these Terms of Service.</p>
              <h2>Access and Use of the Service</h2>
                <p>Services Description: The Service is designed to allow users to both upload and view real-time video content, photos, comments, profiles, descriptions of businesses and locations, and chat messages.</p>
              <h2>Your Registration Obligations:</h2>
                <p>You may be required to register with Keychn in order to access and use certain features of the Service. If you choose to register for the Service, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Service’s registration form. Registration data and certain other information about you are governed by our Privacy Policy. If you are under 13 years of age, you are not authorized to use the Service, with or without registering. In addition, if you are under 18 years old, you may use the Service, with or without registering, only with the approval of your parent or guardian.</p>
              <h2>Member Account, Password and Security:</h2>
                <p>You are responsible for maintaining the confidentiality of your password and account, if any, and are fully responsible for any and all activities that occur under your password or account. You agree to (a) immediately notify Keychn of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session when accessing the Service. Keychn will not be liable for any loss or damage arising from your failure to comply with this Section.</p>
              <h2>Modifications to Service:</h2>
                <p>Keychn reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Keychn will not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
              <h2>General Practices Regarding Use and Storage:</h2>
                <p>You acknowledge that Keychn may establish general practices and limits concerning use of the Service, including without limitation the maximum period of time that data or other content will be retained by the Service and the maximum storage space that will be allotted on Keychn’s servers on your behalf. You agree that Keychn has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Service. You acknowledge that Keychn reserves the right to terminate accounts that are inactive for an extended period of time. You further acknowledge that Keychn reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</p>
              <h2>Mobile Services:</h2>
                <p>The Service includes certain services that are available via a mobile device, including (i) the ability to upload content to the Service via a mobile device, (ii) the ability to browse the Service and the Site from a mobile device and (iii) the ability to access certain features through an application downloaded and installed on a mobile device (collectively, the “Mobile Services”). To the extent you access the Service through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services may work with all carriers or devices. By using the Mobile Services, you agree that we may communicate with you regarding Keychn and other entities by SMS, MMS, text message or other electronic means to your mobile device and that certain information about your usage of the Mobile Services may be communicated to us. In the event you change or deactivate your mobile telephone number, you agree to promptly update your Keychn account information to ensure that your messages are not sent to the person that acquires your old number.</p>
              <h2>Conditions of Use:</h2>
                <h3>User Conduct:</h3>
                  <p>User Conduct: You are solely responsible for all code, video, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials (“content”) that you upload, post, publish or display (hereinafter, “upload”) or email or otherwise use via the Service. The following are examples of the kind of content and/or use that is illegal or prohibited by Keychn. Keychn reserves the right to investigate and take appropriate legal action against anyone who, in Keychn’s sole discretion, violates this provision, including without limitation, removing the offending content from the Service, suspending or terminating the account of such violators and reporting you to the law enforcement authorities. You agree to not use the Service to:
                  a.	email or otherwise upload any content that:
                  i.	infringes any intellectual property or other proprietary rights of any party;
                  ii.	you do not have a right to upload under any law or under contractual or fiduciary relationships;
                  iii.	contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;
                  iv.	poses or creates a privacy or security risk to any person;
                  v.	constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation;
                  vi.	is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically or otherwise objectionable; or
                  vii.	in the sole judgment of Keychn, is objectionable or which restricts or inhibits any other person from using or enjoying the Service, or which may expose Keychn or its users to any harm or liability of any type;
                  b.	interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service; or
                  c.	violate any applicable local, state, national or international law, or any regulations having the force of law;
                  d.	impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;
                  e.	solicit personal information from anyone under the age of 18;
                  f.	harvest or collect email addresses or other contact information of other users from the Service by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;
                  g.	advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized;
                  h.	further or promote any criminal activity or enterprise or provide instructional information about illegal activities; or
                  i.	obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Service.
                  </p>
                <h2>Special Notice for International Use; Export Controls:</h2>
                  <p>Software (defined below) available in connection with the Service and the transmission of applicable data, if any, is subject to United States export controls. No Software may be downloaded from the Service or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the Software is at your sole risk. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the Service, including as it concerns online conduct and acceptable content.</p>
                <h2>Commercial Use: </h2>
                  <p>Unless otherwise expressly authorized herein or in the Service, you agree not to display, distribute, license, perform, publish, reproduce, duplicate, copy, create derivative works from, modify, sell, resell, exploit, transfer or upload for any commercial purposes, any portion of the Service, use of the Service, or access to the Service. The Service is for your personal use.</p>
                <h2>No Endorsement:</h2>
                <p>Keychn does not endorse any content submitted to the Service by any user or third party or any opinion, recommendation or advice expressed therein.</p>
                <h2>Apple-Enabled Software Applications</h2>
                  <p>Keychn offers Software applications that are intended to be operated in connection with products made commercially available by Apple Inc. (“Apple”), among other platforms. With respect to Software that is made available for your use in connection with an Apple-branded product (such Software, “Apple-Enabled Software”), in addition to the other terms and conditions set forth in these Terms of Service, the following terms and conditions apply:
                  •	Keychn and you acknowledge that these Terms of Service are concluded between Keychn and you only, and not with Apple, and that as between Keychn and Apple, Keychn, not Apple, is solely responsible for the Apple-Enabled Software and the content thereof.
                  •	You may not use the Apple-Enabled Software in any manner that is in violation of or inconsistent with the Usage Rules set forth for Apple-Enabled Software in, or otherwise be in conflict with, the App Store Terms of Service.
                  •	Your license to use the Apple-Enabled Software is limited to a non-transferable license to use the Apple-Enabled Software on an iOS Product that you own or control, as permitted by the Usage Rules set forth in the App Store Terms of Service.
                  •	Apple has no obligation whatsoever to provide any maintenance or support services with respect to the Apple-Enabled Software.
                  •	Apple is not responsible for any product warranties, whether express or implied by law. In the event of any failure of the Apple-Enabled Software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Apple-Enabled Software to you, if any; and, to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the Apple-Enabled Software, or any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty, which will be Keychn’s sole responsibility, to the extent it cannot be disclaimed under applicable law.
                  •	Keychn and you acknowledge that Keychn, not Apple, is responsible for addressing any claims of you or any third party relating to the Apple-Enabled Software or your possession and/or use of that Apple-Enabled Software, including, but not limited to:
                  i.	product liability claims;
                  ii.	any claim that the Apple-Enabled Software fails to conform to any applicable legal or regulatory requirement; and
                  iii.	claims arising under consumer protection or similar legislation.
                  •	In the event of any third party claim that the Apple-Enabled Software or the end-user’s possession and use of that Apple-Enabled Software infringes that third party’s intellectual property rights, as between Keychn and Apple, Keychn, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim.
                  •	You represent and warrant that
                  i.	you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and
                  ii.	you are not listed on any U.S. Government list of prohibited or restricted parties.
                  •	If you have any questions, complaints or claims with respect to the Apple-Enabled Software, they should be directed to Keychn as follows: email support@Keychn.com .
                  Keychn and you acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms of Service with respect to the Apple-Enabled Software, and that, upon your acceptance of the terms and conditions of these Terms of Service, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms of Service against you with respect to the Apple-Enabled Software as a third party beneficiary thereof.
                  </p>
                <h2>Intellectual Property Rights</h2><h3>Service Content, Software and Trademarks:</h3>
                  <p>You acknowledge and agree that the Service may contain content or features (“Service Content”) that are protected by copyright, patent, trademark, trade secret or other proprietary rights and laws. Except as expressly authorized by Keychn, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Service Content, in whole or in part, except that the foregoing does not apply to your own User Content (as defined below) that you legally upload to the Service. In connection with your use of the Service you will not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. If you are blocked by Keychn from accessing the Service (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address). Any use of the Service or the Service Content other than as specifically authorized herein is strictly prohibited. The technology and software underlying the Service or distributed in connection therewith are the property of Keychn, our affiliates and our partners (the “Software”). You agree not to copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Software. Any rights not expressly granted herein are reserved by Keychn.
                  The Keychn name and logos are trademarks and service marks of Keychn (collectively the “Keychn Trademarks”). Other company, product, and service names and logos used and displayed via the Service may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to Keychn. Nothing in this Terms of Service or the Service should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of Keychn Trademarks displayed on the Service, without our prior written permission in each instance. All goodwill generated from the use of Keychn Trademarks will inure to our exclusive benefit.
                  </p>
                    <h3>Third Party Material:</h3>
                      <p>Under no circumstances will Keychn be liable in any way for any content or materials of any third parties (including users), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. You acknowledge that Keychn does not pre-screen content, but that Keychn and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Service. Without limiting the foregoing, Keychn and its designees will have the right to remove any content that violates these Terms of Service or is deemed by Keychn, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content.
                      User Content Transmitted Through the Service: With respect to the content or other materials you upload through the Service or share with other users or recipients (collectively, “User Content”), you represent and warrant that you own all right, title and interest in and to such User Content, including, without limitation, all copyrights and rights of publicity contained therein. By uploading any User Content you hereby grant and will grant Keychn and its affiliated companies a nonexclusive, worldwide, royalty free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use your User Content in connection with the operation of the Service or the promotion, advertising or marketing thereof in any form, medium or technology now known or later developed.
                      You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Service (“Submissions”), provided by you to Keychn are non-confidential and Keychn will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.
                      You acknowledge and agree that Keychn may preserve content and may also disclose content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms of Service; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Keychn, its users and the public. You understand that the technical processing and transmission of the Service, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.
                      Copyright Complaints: Keychn respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, you should notify Keychn of your infringement claim in accordance with the procedure set forth below.
                      Keychn will process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act (“DMCA”) and other applicable intellectual property laws with respect to any alleged or actual infringement. A notification of claimed copyright infringement should be emailed to Keychn’s Copyright Agent at dmca@Keychn.com (Subject line: “DMCA Takedown Request”). You may also contact us by mail or facsimile at: 14 Rec Comtal 2-2, Barcelona, SP 08003 .
                      To be effective, the notification must be in writing and contain the following information:
                      •	an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;
                      •	a description of the copyrighted work or other intellectual property that you claim has been infringed;
                      •	a description of where the material that you claim is infringing is located on the Service, with enough detail that we may find it on the Service;
                      •	your address, telephone number, and email address;
                      •	a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;
                      •	a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.
                      </p>
                <h2>Claim Copyright Infringement</h2>
                  <h3>Counter-Notice: </h3>
                  <p>If you believe that your User Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to upload and use the content in your User Content, you may send a written counter-notice containing the following information to the Copyright Agent:
                  •	your physical or electronic signature;
                  •	identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;
                  •	a statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content; and
                  •	your name, address, telephone number, and email address, a statement that you consent to the jurisdiction of the federal court located within Northern District of California and a statement that you will accept service of process from the person who provided notification of the alleged infringement.
                  If a counter-notice is received by the Copyright Agent, Keychn will send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion.
                  Repeat Infringer Policy: In accordance with and other applicable law, Keychn has adopted a policy of terminating, in appropriate circumstances and at Keychn's sole discretion, users who are deemed to be repeat infringers. Keychn may also at its sole discretion limit access to the Service and/or terminate the memberships of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.
                  For more information on other content removal processes supported by Keychn, please visit our privacy policy, located at https://Keychn.com/privacy .
                  </p>
                <h2>Third Party Websites</h2>
                  <p>The Service may provide, or third parties may provide, links or other access (including, but not limited to the ability to re-post content) to other sites and resources on the Internet. Keychn has no control over such sites and resources and Keychn is not responsible for and does not endorse such sites and resources. You further acknowledge and agree that Keychn will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site or resource. Any dealings you have with third parties found while using the Service are between you and the third party, and you agree that Keychn is not liable for any loss or claim that you may have against any such third party.
                </p>
                <h2>Social Networking Services:</h2>
                  <p>You may enable or log in to the Service via various online third party services, such as social media and social networking services like Facebook or Twitter (“Social Networking Services”). By logging in or directly integrating these Social Networking Services into the Service, we make your online experiences richer and more personalized. To take advantage of this feature and capabilities, we may ask you to authenticate, register for or log into Social Networking Services on the websites of their respective providers. As part of such integration, the Social Networking Services will provide us with access to certain information that you have provided to such Social Networking Services, and we will use, store and disclose such information in accordance with our Privacy Policy. For more information about the implications of activating these Social Networking Services and Keychn’s use, storage and disclosure of information related to you and your use of such services within Keychn (including your friend lists and the like), please see our Privacy Policy at www.Keychn.com/privacy . However, please remember that the manner in which Social Networking Services use, store and disclose your information is governed solely by the policies of such third parties, and Keychn shall have no liability or responsibility for the privacy practices or other actions of any third party site or service that may be enabled within the Service.
                  In addition, Keychn is not responsible for the accuracy, availability or reliability of any information, content, goods, data, opinions, advice or statements made available in connection with Social Networking Services. As such, Keychn is not liable for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Social Networking Services. Keychn enables these features merely as a convenience and the integration or inclusion of such features does not imply an endorsement or recommendation.
                  </p>
              <h2>Indemnity and Release</h2>
                <p>You agree to release, indemnify and hold Keychn and its affiliates and their officers, employees, directors and agents harmless from any from any and all losses, damages, expenses, including reasonable attorneys’ fees, rights, claims, actions of any kind and injury (including death) arising out of or relating to your use of the Service, any User Content, your connection to the Service, your violation of these Terms of Service or your violation of any rights of another (including, without limitation any copyright, property or privacy right). If you are a California resident, you waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.” If you are a resident of another jurisdiction, you waive any comparable statute or doctrine. This defense and indemnification obligation will survive these Terms of Service and your use of the Service.
                </p>
              <h2>Disclaimer of Warranties</h2>
                <p>YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. KEYCHN, KEYCHN AFFILIATES, KEYCHN OFFICERS, DIRECTORS, EMPLOYEES AND AGENTS AND THE SAME OF ITS AFFILIATES EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.
                COMPANY MAKES NO WARRANTY THAT (I) THE SERVICE WILL MEET YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, OR (V) THE CONTENT OR ANY SITES LINKED TO THE SITE WILL BE ACCURATE OR COMPLETE.
                KEYCHN DOES NOT WARRANT, ENDORSE, GUARANTEE OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY OTHER TYPE OF ADVERTISING THROUGH THE SERVICES (WHETHER OR NOT PERMITTED). KEYCHN IS NOT AND SHALL NOT BE A PARTY TO OR IN ANY WAY RESPONSIBLE FOR ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY.
                The Service is controlled, hosted, maintained and offered by Keychn from its facilities in Spain. Keychn makes no representations that the Service is appropriate for use in other locations. Those who access or use the Services from other jurisdictions assume their own risk in doing so and are responsible for compliance with local law.
                </p>
              <h2>Limitation of Liability</h2>
                <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT KEYCHN AND ITS AFFILIATES (AND ANY OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS OF KEYCHN OR ITS AFFILIATES) WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM: (I) THE USE OR THE INABILITY TO USE THE SERVICE; (II) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (III) UNAUTHORIZED ACCESS TO, USE OF OR ALTERATION OF YOUR TRANSMISSIONS, DATA OR CONTENT (INCLUDING, BUT NOT LIMITED TO PERSONAL IMFORMATION AND FINANCIAL INFORMATION); (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; (V) ERRORS, MISTAKES OR INACCURACIES OF ANY CONTENT MADE AVAILABLE IN CONNECTION WITH THE SERVICES; (V) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES; (VI) ANY BUGS, VIRUSES, TROJAN HORSES OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY; OR (VII) ANY OTHER MATTER RELATING TO THE SERVICE.
                SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.
                </p>
              <h2>Arbitration</h2>
                <p>At Keychn’s or your election, all disputes, claims, or controversies arising out of or relating to the Terms of Service or the Service that are not resolved by mutual agreement may be resolved by binding arbitration to be conducted before JAMS, or its successor. Unless otherwise agreed by the parties, arbitration will be held in Barcelona,Spain. before a single arbitrator mutually agreed upon by the parties, or if the parties cannot mutually agree, a single arbitrator appointed by JAMS, and will be conducted in accordance with the rules and regulations promulgated by JAMS unless specifically modified in the Terms of Service. The arbitration must commence within forty- five (45) days of the date on which a written demand for arbitration is filed by either party. The arbitrator’s decision and award will be made and delivered within sixty (60) days of the conclusion of the arbitration and within six (6) months of the selection of the arbitrator. The arbitrator will not have the power to award damages in excess of the limitation on actual compensatory, direct damages set forth in the Terms of Service and may not multiply actual damages or award punitive damages or any other damages that are specifically excluded under the Terms of Service, and each party hereby irrevocably waives any claim to such damages. The arbitrator may, in his or her discretion, assess costs and expenses (including the reasonable legal fees and expenses of the prevailing part) against any party to a proceeding. Any party refusing to comply with an order of the arbitrators will be liable for costs and expenses, including attorneys’ fees, incurred by the other party in enforcing the award. Notwithstanding the foregoing, in the case of temporary or preliminary injunctive relief, any party may proceed in court without prior arbitration for the purpose of avoiding immediate and irreparable harm. The provisions of this arbitration section will be enforceable in any court of competent jurisdiction.
                Notwithstanding the provisions of the introductory section above, if Keychn changes this ‘Arbitration’ section after the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service ), you may reject any such change by sending us written notice within 30 days of the date such change became effective, as indicated in the “Date of Last Revision” date above or in the date of Keychn’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any dispute between you and Keychn in accordance with the provisions of this section as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).
                </p>
              <h2>Termination</h2>
                <p>You agree that Keychn, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Service and remove and discard any content within the Service, for any reason, including, without limitation, for lack of use or if Keychn believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Service, may be referred to appropriate law enforcement authorities. Keychn may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. You agree that any termination of your access to the Service under any provision of this Terms of Service may be effected without prior notice, and acknowledge and agree that Keychn may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Service. Further, you agree that Keychn will not be liable to you or any third party for any termination of your access to the Service.
                </p>
              <h2>User Disputes</h2>
                <p>You agree that you are solely responsible for your interactions with any other user in connection with the Service and Keychn will have no liability or responsibility with respect thereto. Keychn reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Service.
                </p>
              <h2>General</h2>
                <p>These Terms of Service constitute the entire agreement between you and Keychn and govern your use of the Service, superseding any prior agreements between you and Keychn with respect to the Service. You also may be subject to additional terms and conditions that may apply when you use affiliate or third party services, third party content or third party software. These Terms of Service will be governed by the laws of the State of California without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and Keychn agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within San Francisco County, California. The failure of Keychn to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision. If any provision of these Terms of Service is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms of Service remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or these Terms of Service must be filed within one (1) year after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You may not assign this Terms of Service without the prior written consent of Keychn, but Keychn may assign or transfer this Terms of Service, in whole or in part, without restriction. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Service may also provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the Service.
                </p>
              <h2>Your Privacy</h2>
                <p>At Keychn, we respect the privacy of our users. For details please see our Privacy Policy. By using the Service, you consent to our collection and use of personal data as outlined therein.
                </p>
              <h2>Questions?  Concerns?  Suggestions?</h2>
                <p>Please contact us at support@Keychn.com to report any violations of these Terms of Service or to pose any questions regarding this Terms of Service or the Service.
                </p>
              <h2>Copyright</h2>
                <p>© 2016 Keychn Experience SL. All rights reserved. Keychn, and the Keychn logo, are trademarks and/or registered trademarks of Keychn Experience SL. All other trademarks are property of their respective owners.
                </p>
            </div>
          </main>
        </div>
        <div className="col-md-2"></div>
      </div>
      <Footer />
    </div>
  )
}

module.exports = Terms
